### ISSUE TITLE
1.0.4 is built with a way too recent glibc version, making it incompatible with most LTS server OS.

### ISSUE THREAD

**Issue by Kodehawa** [BOOMfinity-Developers/GoThink#5]
Seems like 1.0.4 supports a minimum of glibc 2.32. Debian 10 uses 2.28. Please consider lowering the glibc you use to compile this package, as of now it's pretty much impossible to run it in a server environment.

![image](https://user-images.githubusercontent.com/20606963/187519876-d86b3440-337f-40b2-bd2b-35d7e41bfab5.png)

EDIT: 1.0.4a release works under Debian 10.

**Comment by MrBoombastic** [comment]
FTR: fixed in v1.0.4b
